# Old configuration for MySQL
#  development:
#    adapter: mysql2
#    encoding: utf8
#    reconnect: false
#    database: phonebook_development
#    pool: 5
#    username: root
#    password: root
#    socket: /tmp/mysql.sock

development:
  adapter: postgresql
  encoding: utf8
  database: phonebook_development
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: utf8
  database: phonebook_test
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: utf8
  database: phonebook_production
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1